server:
  port: 8888
spring:
  application:
    name: base-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Seale6/SpringConfigTest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/